/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as FriendsIndexRouteImport } from './routes/friends/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ActivityIndexRouteImport } from './routes/activity/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as SettleNewRouteImport } from './routes/settle/new'
import { Route as GroupsGroupIdRouteImport } from './routes/groups/$groupId'
import { Route as ExpenseNewRouteImport } from './routes/expense/new'
import { Route as authVerifyEmailIndexRouteImport } from './routes/(auth)/verify-email/index'
import { Route as authResetPasswordIndexRouteImport } from './routes/(auth)/reset-password/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as authForgotPasswordIndexRouteImport } from './routes/(auth)/forgot-password/index'
import { Route as GroupsGroupIdSettingsRouteImport } from './routes/groups/$groupId/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsIndexRoute = FriendsIndexRouteImport.update({
  id: '/friends/',
  path: '/friends/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettleNewRoute = SettleNewRouteImport.update({
  id: '/settle/new',
  path: '/settle/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseNewRoute = ExpenseNewRouteImport.update({
  id: '/expense/new',
  path: '/expense/new',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailIndexRoute = authVerifyEmailIndexRouteImport.update({
  id: '/(auth)/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordIndexRoute = authResetPasswordIndexRouteImport.update({
  id: '/(auth)/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordIndexRoute = authForgotPasswordIndexRouteImport.update({
  id: '/(auth)/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdSettingsRoute = GroupsGroupIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/expense/new': typeof ExpenseNewRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/settle/new': typeof SettleNewRoute
  '/account/': typeof AccountIndexRoute
  '/activity/': typeof ActivityIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/friends/': typeof FriendsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/forgot-password/': typeof authForgotPasswordIndexRoute
  '/login/': typeof authLoginIndexRoute
  '/register/': typeof authRegisterIndexRoute
  '/reset-password/': typeof authResetPasswordIndexRoute
  '/verify-email/': typeof authVerifyEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/expense/new': typeof ExpenseNewRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/settle/new': typeof SettleNewRoute
  '/account': typeof AccountIndexRoute
  '/activity': typeof ActivityIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/friends': typeof FriendsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/verify-email': typeof authVerifyEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/expense/new': typeof ExpenseNewRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/settle/new': typeof SettleNewRoute
  '/account/': typeof AccountIndexRoute
  '/activity/': typeof ActivityIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/friends/': typeof FriendsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/(auth)/forgot-password/': typeof authForgotPasswordIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(auth)/reset-password/': typeof authResetPasswordIndexRoute
  '/(auth)/verify-email/': typeof authVerifyEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/expense/new'
    | '/groups/$groupId'
    | '/settle/new'
    | '/account/'
    | '/activity/'
    | '/dashboard/'
    | '/friends/'
    | '/groups/'
    | '/api/auth/$'
    | '/groups/$groupId/settings'
    | '/forgot-password/'
    | '/login/'
    | '/register/'
    | '/reset-password/'
    | '/verify-email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/expense/new'
    | '/groups/$groupId'
    | '/settle/new'
    | '/account'
    | '/activity'
    | '/dashboard'
    | '/friends'
    | '/groups'
    | '/api/auth/$'
    | '/groups/$groupId/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/expense/new'
    | '/groups/$groupId'
    | '/settle/new'
    | '/account/'
    | '/activity/'
    | '/dashboard/'
    | '/friends/'
    | '/groups/'
    | '/api/auth/$'
    | '/groups/$groupId/settings'
    | '/(auth)/forgot-password/'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/(auth)/reset-password/'
    | '/(auth)/verify-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ExpenseNewRoute: typeof ExpenseNewRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRouteWithChildren
  SettleNewRoute: typeof SettleNewRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  FriendsIndexRoute: typeof FriendsIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  authForgotPasswordIndexRoute: typeof authForgotPasswordIndexRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
  authResetPasswordIndexRoute: typeof authResetPasswordIndexRoute
  authVerifyEmailIndexRoute: typeof authVerifyEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/': {
      id: '/friends/'
      path: '/friends'
      fullPath: '/friends/'
      preLoaderRoute: typeof FriendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settle/new': {
      id: '/settle/new'
      path: '/settle/new'
      fullPath: '/settle/new'
      preLoaderRoute: typeof SettleNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/new': {
      id: '/expense/new'
      path: '/expense/new'
      fullPath: '/expense/new'
      preLoaderRoute: typeof ExpenseNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email/': {
      id: '/(auth)/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof authVerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password/': {
      id: '/(auth)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof authResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password/': {
      id: '/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof authForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/settings': {
      id: '/groups/$groupId/settings'
      path: '/settings'
      fullPath: '/groups/$groupId/settings'
      preLoaderRoute: typeof GroupsGroupIdSettingsRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GroupsGroupIdRouteChildren {
  GroupsGroupIdSettingsRoute: typeof GroupsGroupIdSettingsRoute
}

const GroupsGroupIdRouteChildren: GroupsGroupIdRouteChildren = {
  GroupsGroupIdSettingsRoute: GroupsGroupIdSettingsRoute,
}

const GroupsGroupIdRouteWithChildren = GroupsGroupIdRoute._addFileChildren(
  GroupsGroupIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ExpenseNewRoute: ExpenseNewRoute,
  GroupsGroupIdRoute: GroupsGroupIdRouteWithChildren,
  SettleNewRoute: SettleNewRoute,
  AccountIndexRoute: AccountIndexRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  FriendsIndexRoute: FriendsIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  authForgotPasswordIndexRoute: authForgotPasswordIndexRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
  authResetPasswordIndexRoute: authResetPasswordIndexRoute,
  authVerifyEmailIndexRoute: authVerifyEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
